import os
import subprocess
import re
import shutil
import gen_testbench

def run_hope(bench_file):
    #print(f"Running HOPE on {bench_file}")
    # Use relative path and shell=True to avoid path issues
    cmd = f"HOPE\\hope.exe -s 9999 -r 10000 -D -l WORKING\\hope_temp.log {bench_file}"
    with open("WORKING\\hope_stdout.log", "w") as outfile:
        subprocess.run(cmd, stdout=outfile, stderr=subprocess.STDOUT, check=True, shell=True)
    return True

def find_best_candidate(log_file, forbidden_nodes):
    fault_counts = {}
    fault_pattern = re.compile(r'\s+([a-zA-Z0-9_>\-]+)\s+/[01]')

    with open(log_file, 'r') as f:
        for line in f:
            match = fault_pattern.search(line)
            if match:
                raw_name = match.group(1)
                node = raw_name.split('->')[-1] 
                
                if node in forbidden_nodes: 
                    continue
                if "pre" in node: # ignore pre nodes
                    continue
                if "in" in node: # ignore inputs
                    continue
                if "out" in node: # ignore outputs
                    continue
                if "k" in node: # ignore keys we created
                    continue
                    
                fault_counts[node] = fault_counts.get(node, 0) + 1

    sorted_nodes = sorted(fault_counts.items(), key=lambda x: x[1], reverse=True)
    #print(sorted_nodes)
    return sorted_nodes[0]

def copy_to_unix(src, dst):
    with open(src, 'r') as f_src:
        content = f_src.read()
    with open(dst, 'w', newline='\n') as f_dst:
        f_dst.write(content)

def insert_gate(input_file, output_file, target_node, key_idx):
    with open(input_file, 'r') as f:
        lines = f.readlines()

    new_lines = []
    key_name = f"k{key_idx}"
    seenOutput = False
    
    def_pattern = re.compile(rf"^\s*{re.escape(target_node)}\s*=")

    for line in lines:
        if line.strip().startswith("OUTPUT") and not seenOutput:
            seenOutput = True
            new_lines.append(f"INPUT({key_name})\n")
            new_lines.append(line)
            continue
            
        if def_pattern.match(line):
            parts = line.split('=')
            logic = parts[1].strip()
            # print("Appending following lines:")
            # print(f"{target_node}pre = {logic}")
            # print(f"{target_node} = XOR({target_node}pre, {key_name})")
            new_lines.append(f"{target_node}pre = {logic}\n")
            new_lines.append(f"{target_node} = XOR({target_node}pre, {key_name})\n")
        else:
            new_lines.append(line)

    with open(output_file, 'w', newline='\n') as f:
        f.writelines(new_lines)
    
    return True

def run_abc_conversion(bench_input, verilog_output, module_name=None):
    print(f"\nConverting {bench_input} to {verilog_output} with ABC")
    shutil.copy(bench_input, module_name + ".bench")
    cmd = f"ABC\\abc10216.exe -c \"read_bench {module_name}.bench; write_verilog {os.path.abspath(verilog_output)};\""
    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL) #supress output
    print(f"Verilog file generated by ABC: {verilog_output}")
    os.remove(module_name + ".bench")
    return True

if __name__ == "__main__":
    num_keys = int(input("Key Gates?: "))
    copy_to_unix("WORKING\\c432.bench", "WORKING\\current_design.bench")
    forbidden_nodes = set()
    
    for k in range(num_keys):
        print(f"Locking key {k+1} out of {num_keys}: ", end="")
        run_hope("WORKING\\current_design.bench")
        candidate, impact = find_best_candidate("WORKING\\hope_temp.log", forbidden_nodes)
        if not candidate:
            print("no candidates for locking found")
            break
        print(f"{candidate} selected for locking, impact = {impact}")
        insert_gate("WORKING\\current_design.bench", "WORKING\\current_design.bench", candidate, k)
        forbidden_nodes.add(candidate)

    copy_to_unix("WORKING\\current_design.bench", "WORKING\\c432_secure.bench")
    print(f"\nFinal locked netlist saved to: c432_secure.bench")
    run_abc_conversion("WORKING\\c432_secure.bench", "TEST\\c432_secure.v", module_name="c432_secure")
    run_abc_conversion("WORKING\\c432.bench", "TEST\\c432.v", module_name="c432_default")
    
    print(f"\nGenerating Testbench")
    gen_testbench.generate_testbench(num_keys)


